version: '3.5'
services:
  weixin_contact:
    image: weixin
    environment:
      - CorPID=${CorPID}
      - ContactSecret=${ContactSecret}
      - ContactToken=${ContactToken}
      - ContactAesKey=${ContactAesKey}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    command: ./bin/contactsrv
    container_name: weixin_contact
    ports:
      - "11110:11110"

networks:
  default:
    external:
      name: weixin_net
