version: '3.5'
services:
  mysql_db:
    image: mysql:8.0.18
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    privileged: true
    ports:
      - 3306:3306
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
      MYSQL_DATABASE: weixin

  redis_db:
    image: redis:5.0.7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    privileged: true
    ports:
      - 6379:6379
    container_name: redis_db

networks:
  default:
    external:
      name: weixin_net